#!/bin/bash
# Setup Supra dVRF V3 for Veil Hub on Supra L1

echo "🌑 Veil Hub dVRF V3 Setup"
echo ""
echo "Step 1: Visit https://supra.com/data/dvrf"
echo "  - Connect StarKey wallet"
echo "  - Create subscription with Max Transaction Fee"
echo "  - Receive Supra Credits grant (covers initial requests)"
echo ""
echo "Step 2: Deploy veil_dvrf module"
echo "  supra move tool publish --profile veil_deployer"
echo ""
echo "Step 3: Module auto-whitelisted via init_module()"
echo "  - Calls deposit::init_vrf_module<VeilVRF>()"
echo "  - Stores SupraVRFPermit capability"
echo ""
echo "Step 4: Request randomness"
echo "  supra move tool run \\"
echo "    --function-id veil_hub::veil_dvrf::request_vault_randomness \\"
echo "    --args u8:1 u64:0 u64:6"
echo ""
echo "Step 5: Monitor balance"
echo "  - Check Supra Credits in UI"
echo "  - Deposit \$SUPRA when grant exhausted"
echo ""
echo "Minimum Balance: max_txn_fee × 30 requests"
